rewrite collective learning goals
MIT-Emerging-Talent/2024-group-11-cdsp pull request #47
Opened 2024-02-16 22:36 UTC by YaninaChukanova

2024-02-16 22:42 UTC, AnnaShliapkina submitted a review, later dismissed

2024-02-16 22:48 UTC, DmytroLyt commented
I would suggest next goals:  


1. Understanding of Machine Learning:
   - Master the basics of machine learning through practical exercises and experiments.
   - Acquire proficiency in implementing machine learning algorithms to solve complex data analysis tasks.
   - Utilize statistical techniques to extract meaningful insights from data and make informed decisions.

2. Code Writing and Documentation:
   - Learn to write clean and well-documented code.
   - Emphasize the importance of writing structured and understandable code in data analysis projects.
   - Document the development process and analysis procedures to facilitate knowledge sharing within the team.

3. Statistical Analysis:
   - Conduct statistical analysis to derive insights from data.
   - Use exploratory data analysis to identify patterns, trends, and insights in a dataset.
   - Enhance the accuracy and impact of findings through collaborative interpretation of data insights.

4. Data Preparation and Quality:
   - Learn how to clean and prepare data for analysis, ensuring data quality and integrity.
   - Gain a deeper understanding of data science methodologies and enhance the structuring of data science workflows.
   - Contribute to the team's success by actively participating in collaborative data science projects.

2024-02-16 22:49 UTC, DmytroLyt requested changes
Need to provide more specific goals. Some suggestion provided in comments

2024-02-16 22:52 UTC, DmytroLyt commented
Also need to assigned to some of existing issue from project backlog

2024-02-18 21:16 UTC, DmytroLyt approved these changes

2024-02-18 21:18 UTC, merged